package com.mct.coreservices;


import com.mct.VehicleInterfaceProperties;
import com.mct.VehiclePropertyConstants;

import android.util.SparseIntArray;

public class OBDProtocol
{
	
	// //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// OBD AT CMD
	public static final String AT_CMD_HEAD											= "AT";
	public static final String AT_CMD_TAIL												= "\r\n";
	public static final String AT_CMD_RESULT_HEAD								= "$";
	public static final String AT_CMD_NO_ENGINE_LOAD						= "004";
	public static final String AT_CMD_NO_COOLANT_TEMP						= "005";
	public static final String AT_CMD_NO_FUEL_PRESSURE					= "010";
	public static final String AT_CMD_NO_INPIPE_PRESSURE					= "011";
	public static final String AT_CMD_NO_ENGINE_SPEED						= "012";
	public static final String AT_CMD_NO_DRIVING_SPEED						= "013";
	public static final String AT_CMD_NO_IGNITION_ANGLE					= "014";
	public static final String AT_CMD_NO_INTAKE_TEMP						= "015";
	public static final String AT_CMD_NO_INTAKE_FLOW_RATE				= "016";
	public static final String AT_CMD_NO_THROTTLE_POSN					= "017";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_POSN			= "019";
	public static final String AT_CMD_NO_ENGINE_RUN_TIME				= "031";
	public static final String AT_CMD_NO_VACUUM_OIL_PRESSURE  		= "034";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B1S1			= "036";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B1S2			= "037";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B2S1			= "038";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B2S2			= "039";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B3S1			= "040";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B3S2			= "041";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B4S1			= "042";
	public static final String AT_CMD_NO_OXYGEN_SENSOR_B4S2			= "043";
	public static final String AT_CMD_NO_EGR_OPEN_DEGREE				= "044";
	public static final String AT_CMD_NO_EVA_CLEAR_OPEN_DEGREE	= "046";
	public static final String AT_CMD_NO_REMAING_FUEL						= "047";
	public static final String AT_CMD_NO_3W_CATALYST_TEMP_B1S1	= "060";
	public static final String AT_CMD_NO_3W_CATALYST_TEMP_B1S2	= "061";
	public static final String AT_CMD_NO_3W_CATALYST_TEMP_B2S1	= "062";
	public static final String AT_CMD_NO_3W_CATALYST_TEMP_B2S2	= "063";
	public static final String AT_CMD_NO_EVA_SYSTEM_PRESSURE		= "084";
	public static final String AT_CMD_NO_VEHICLE_VIN_CODE				= "296";
	public static final String AT_CMD_NO_BATTERY_VOLTAGE				= "297";
	public static final String AT_CMD_NO_CUR_FUEL_CONSUMPTION		= "298";
	public static final String AT_CMD_NO_FUEL_CONSN_HUND_KM			= "299";
	public static final String AT_CMD_NO_ODOMETER_INFO					= "300";
	public static final String AT_CMD_NO_FUEL_CONSUMPTION_INFO	= "301";
	public static final String AT_CMD_NO_TOTAL_ODOMETER_CHECK		= "302";
	public static final String AT_CMD_NO_DRIVING_TIME_INFO				= "303";
	public static final String AT_CMD_NO_MINUS_ODOMETER				= "304";
	public static final String AT_CMD_NO_READ_DTC_CODE					= "400";
	public static final String AT_CMD_NO_CLEAR_DTC_CODE					= "401";
	public static final String AT_CMD_NO_DEVICE_INFO							= "500";
	public static final String AT_CMD_NO_CLEAR_CACHE_DATA				= "501";
	public static final String AT_CMD_NO_RECEIVE_SETTING_STATUS	= "503";
	
	public static final String AT_CMD_RT_DATA_STREAM_ON					= "ATRON";
	public static final String AT_CMD_RT_DATA_STREAM_OFF				= "ATROFF";
	public static final String AT_CMD_DRIVING_HABITS							= "ATHBT\r\n";
	public static final String AT_CMD_COUSTOM_PID_ON						= "ATPIDON\r\n";
	public static final String AT_CMD_COUSTOM_PID_OFF						= "ATPIDOFF\r\n";
	public static final String AT_CMD_BAUD_RATE_9600						= "ATBUD=0\r\n";
	public static final String AT_CMD_BAUD_RATE_38400						= "ATBUD=1\r\n";
	public static final String AT_CMD_BAUD_RATE_115200						= "ATBUD=2\r\n";
	public static final String AT_CMD_ECU_DELAY_CONN_ON					= "ATSDRY";
	public static final String AT_CMD_ECU_DELAY_CONN_OFF				= "ATSDRN";
	public static final String AT_CMD_STARTUP_AUTO							= "ATVCRY\r\n";
	public static final String AT_CMD_STARTUP_MANUAL						= "ATVCRN\r\n";
	public static final String AT_CMD_HOT_RESTART								= "ATWST\r\n";
	public static final String AT_CMD_SLEEP											= "ATSLEEP\r\n";
	
	
	
	public static final String OBD_VEHICLE_RT_DATA_STREAM_HEAD 	= "$OBD-RT";		//实时数据流
	public static final String OBD_DRIVING_HABIT_HEAD 						= "$OBD-HBT";	//驾驶习惯数据
	public static final String OBD_CUR_TRAVEL_DATA_HEAD 					= "$OBD-TT";		//本次行程数据统计
	
	//协议返回的无效数据
	public static final String ECU_NOT_SUPPORT 									= "ECU not support.";


	//权限定义
	public static final int PROPERITY_PERMISSON_NO				= VehiclePropertyConstants.PROPERITY_PERMISSON_NO;			//NOTIFY ONLY
	public static final int PROPERITY_PERMISSON_GET				= VehiclePropertyConstants.PROPERITY_PERMISSON_GET; 			// GET ONLY
	public static final int PROPERITY_PERMISSON_SET				= VehiclePropertyConstants.PROPERITY_PERMISSON_SET; 			// SET ONLY
	public static final int PROPERITY_PERMISSON_GET_SET 	= VehiclePropertyConstants.PROPERITY_PERMISSON_GET_SET;	// GET_SET

	//所有支持的属性集
	public static final int[] VEHICLE_PROPERITIES = new int[] { 
			VehicleInterfaceProperties.VIM_ODOMETER_PROPERTY, 
			VehicleInterfaceProperties.VIM_MALFUNCTION_INDICATOR_PROPERTY,
			VehicleInterfaceProperties.VIM_BATTERY_VOLTAGE_PROPERTY,
			VehicleInterfaceProperties.VIM_RMNG_FUEL_LVL_PROPERTY,
			VehicleInterfaceProperties.VIM_COOLANT_TEMP_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_VIN_PROPERTY,
			VehicleInterfaceProperties.VIM_SPEEDO_METER_PROPERTY,
			VehicleInterfaceProperties.VIM_ENGINE_SPEED_PROPERTY,
			VehicleInterfaceProperties.VIM_TRIP_METER_1_MILEAGE_PROPERTY,
			VehicleInterfaceProperties.VIM_TRIP_METER_2_MILEAGE_PROPERTY,
			VehicleInterfaceProperties.VIM_TRIP_METER_1_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_TRIP_METER_2_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_MEASUREMENT_DISTANCE_PROPERTY,
			VehicleInterfaceProperties.VIM_ENGN_LOAD_PROPERTY,
			VehicleInterfaceProperties.VIM_FUEL_PRESSURE_PROPERTY,
			VehicleInterfaceProperties.VIM_IN_PIPE_PRESSURE_PROPERTY,
			VehicleInterfaceProperties.VIM_IGNITION_ANGLE_PROPERTY,
			VehicleInterfaceProperties.VIM_INTAKE_TEMP_PROPERTY,
			VehicleInterfaceProperties.VIM_INTAKE_FLOW_RATE_PROPERTY,
			VehicleInterfaceProperties.VIM_THROTTLE_POSN_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_POSN_PROPERTY,
			VehicleInterfaceProperties.VIM_ENGN_RUN_TIME_PROPERTY,
			VehicleInterfaceProperties.VIM_VACUUM_OIL_RAIL_PRESSURE_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S1_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S2_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S1_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S2_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S1_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S2_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S1_PROPERTY,
			VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S2_PROPERTY,
			VehicleInterfaceProperties.VIM_EGR_OPEN_DEGREE_PROPERTY,
			VehicleInterfaceProperties.VIM_EVA_CLEAR_OPEN_DEGREE_PROPERTY,
			VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S1_PROPERTY,
			VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S2_PROPERTY,
			VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S1_PROPERTY,
			VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S2_PROPERTY,
			VehicleInterfaceProperties.VIM_EVA_SYSTEM_PRESSURE_PROPERTY,
			VehicleInterfaceProperties.VIM_ENGE_INSTANT_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_CUR_TRIP_IDLING_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_CUR_TRIP_DRIVING_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_HUNDRED_KILOMETERS_AVG_FUEL_CONSUMPTION_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_CUR_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_CUR_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_TOTAL_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_TOTAL_PROPERTY,
			VehicleInterfaceProperties.VIM_TOTAL_IGNITION_TIMES,
			VehicleInterfaceProperties.VIM_AVG_WARM_UP_TIME,
			VehicleInterfaceProperties.VIM_AVG_VECHILE_SPEED,
			VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_VEHICLE_SPEED,
			VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_ENGINE_SPEED,
			VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_UP_TIMES,
			VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_DOWN_TIMES,
			VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_UP_TIMES,
			VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_DOWN_TIMES,
			VehicleInterfaceProperties.VIM_CUR_TRIP_WARM_UP_TIME,
			VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_ENGINE_SPEED,
			VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_VECHILE_SPEED,
			VehicleInterfaceProperties.VIM_VEHICLE_PROTOCOL_NAME_PROPERTY,
			VehicleInterfaceProperties.VIM_VEHICLE_MODULE_SN_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_HW_VERSION_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_SW_VERSION_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_BAUD_RATE_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_RT_DATA_STREAM_STATUS_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_STARTUP_MODE_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_DELAY_CONNECT_STATUS_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_DEVICE_CONNECT_STATUS,
			VehicleInterfaceProperties.VIM_CAN_REQ_COMMAND_PROPERTY,
			VehicleInterfaceProperties.VIM_CAN_DATA_STREAM_UPDATE_PROPERTY
	};
	
	// 属性读写权限表
	public static final SparseIntArray VEHICLE_PROPERITY_PERMISSION_TABLE = new SparseIntArray();
	static
	{
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_ODOMETER_PROPERTY, PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_MALFUNCTION_INDICATOR_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_BATTERY_VOLTAGE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_RMNG_FUEL_LVL_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_COOLANT_TEMP_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_VIN_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_SPEEDO_METER_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_ENGINE_SPEED_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_1_MILEAGE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_2_MILEAGE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_1_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_2_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_MEASUREMENT_DISTANCE_PROPERTY,PROPERITY_PERMISSON_SET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_ENGN_LOAD_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_FUEL_PRESSURE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_IN_PIPE_PRESSURE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_IGNITION_ANGLE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_INTAKE_TEMP_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_INTAKE_FLOW_RATE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_THROTTLE_POSN_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_POSN_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_ENGN_RUN_TIME_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VACUUM_OIL_RAIL_PRESSURE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_EGR_OPEN_DEGREE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_EVA_CLEAR_OPEN_DEGREE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S1_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S2_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_EVA_SYSTEM_PRESSURE_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_ENGE_INSTANT_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_DRIVING_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_IDLING_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_HUNDRED_KILOMETERS_AVG_FUEL_CONSUMPTION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_CUR_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_CUR_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_TOTAL_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_TOTAL_PROPERTY,PROPERITY_PERMISSON_GET);

		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_IGNITION_TIMES,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_AVG_WARM_UP_TIME,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_AVG_VECHILE_SPEED,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_VEHICLE_SPEED,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_ENGINE_SPEED,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_UP_TIMES,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_DOWN_TIMES,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_UP_TIMES,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_DOWN_TIMES,PROPERITY_PERMISSON_GET);
		
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_WARM_UP_TIME,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_ENGINE_SPEED,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_VECHILE_SPEED,PROPERITY_PERMISSON_GET);
		
		
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_PROTOCOL_NAME_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_MODULE_SN_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_HW_VERSION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_SW_VERSION_PROPERTY,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_BAUD_RATE_PROPERTY,PROPERITY_PERMISSON_SET);
		
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_RT_DATA_STREAM_STATUS_PROPERTY,PROPERITY_PERMISSON_GET_SET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_STARTUP_MODE_PROPERTY,PROPERITY_PERMISSON_GET_SET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_DELAY_CONNECT_STATUS_PROPERTY,PROPERITY_PERMISSON_GET_SET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_DEVICE_CONNECT_STATUS,PROPERITY_PERMISSON_GET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_REQ_COMMAND_PROPERTY,PROPERITY_PERMISSON_SET);
		VEHICLE_PROPERITY_PERMISSION_TABLE.put(VehicleInterfaceProperties.VIM_CAN_DATA_STREAM_UPDATE_PROPERTY,PROPERITY_PERMISSON_NO);
	}

	// 属性值类型表
	public static final SparseIntArray VEHICLE_PROPERITY_DATA_TYPE_TABLE = new SparseIntArray();
	static
	{
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_ODOMETER_PROPERTY, VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_MALFUNCTION_INDICATOR_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_BATTERY_VOLTAGE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_RMNG_FUEL_LVL_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_COOLANT_TEMP_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_VIN_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_SPEEDO_METER_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_ENGINE_SPEED_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_1_MILEAGE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_2_MILEAGE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_1_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TRIP_METER_2_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_MEASUREMENT_DISTANCE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_ENGN_LOAD_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_FUEL_PRESSURE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_IN_PIPE_PRESSURE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_IGNITION_ANGLE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_INTAKE_TEMP_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_INTAKE_FLOW_RATE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_THROTTLE_POSN_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_POSN_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_ENGN_RUN_TIME_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VACUUM_OIL_RAIL_PRESSURE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B1S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B2S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B3S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_OXYGEN_SENSOR_B4S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_EGR_OPEN_DEGREE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_EVA_CLEAR_OPEN_DEGREE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B1S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S1_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_THREE_WAY_CATALYST_TEMP_B2S2_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_EVA_SYSTEM_PRESSURE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_ENGE_INSTANT_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_IDLING_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_DRIVING_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_HUNDRED_KILOMETERS_AVG_FUEL_CONSUMPTION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_CUR_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_CUR_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_IDLE_TIME_TOTAL_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_DRIVING_TIME_TOTAL_PROPERTY,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_IGNITION_TIMES,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_AVG_WARM_UP_TIME,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_AVG_VECHILE_SPEED,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_VEHICLE_SPEED,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_HISTORY_HIGHEST_ENGINE_SPEED,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_UP_TIMES,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_QUICK_SPEED_DOWN_TIMES,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_UP_TIMES,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_TOTAL_TRIP_QUICK_SPEED_DOWN_TIMES,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_WARM_UP_TIME,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_ENGINE_SPEED,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CUR_TRIP_HIGEST_VECHILE_SPEED,VehiclePropertyConstants.DATA_TYPE_FLOAT);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_PROTOCOL_NAME_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_VEHICLE_MODULE_SN_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_HW_VERSION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_SW_VERSION_PROPERTY,VehiclePropertyConstants.DATA_TYPE_STRING);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_BAUD_RATE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_RT_DATA_STREAM_STATUS_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_STARTUP_MODE_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_DEVICE_CONNECT_STATUS,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_DELAY_CONNECT_STATUS_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
		VEHICLE_PROPERITY_DATA_TYPE_TABLE.put(VehicleInterfaceProperties.VIM_CAN_REQ_COMMAND_PROPERTY,VehiclePropertyConstants.DATA_TYPE_INTEGER);
	}

	public static int getProperityDataType(int prop)
	{
		return (VEHICLE_PROPERITY_DATA_TYPE_TABLE.indexOfKey(prop) >= 0) ? VEHICLE_PROPERITY_DATA_TYPE_TABLE.get(prop) : -1;
	}

	public static int getProperityPermission(int prop)
	{
		return (VEHICLE_PROPERITY_PERMISSION_TABLE.indexOfKey(prop) >= 0) ? VEHICLE_PROPERITY_PERMISSION_TABLE.get(prop) : -1;
	}
	
	public static String addTail(String cmdNo)
	{
		return cmdNo+AT_CMD_TAIL;
	}
	
	public static String getATCmd(String cmdNo)
	{
		return AT_CMD_HEAD+cmdNo+AT_CMD_TAIL;
	}
	
	public static String getATCmd(String cmdNo,String value)
	{
		return AT_CMD_HEAD+cmdNo+"="+value+AT_CMD_TAIL;
	}
}
