package com.mct.deviceservices;

import com.mct.DeviceInterfaceProperties;
import com.mct.DevicePropertyConstants;

import android.util.SparseIntArray;

public class InterPhoneProtocol
{

	// Data types associated with properties.
	public static final int DATA_TYPE_UNKNOWN 						= 0;
	public static final int DATA_TYPE_INTEGER 						= 1;
	public static final int DATA_TYPE_FLOAT 							= 2;
	public static final int DATA_TYPE_STRING 							= 3;	
	public static final int DATA_TYPE_INT_ARRAY 					= 4;	
	public static final int DATA_TYPE_FLOAT_ARRAY 				= 5;	
	public static final int DATA_TYPE_STRING_ARRAY 				= 6;		
			
	//权限定义
	public static final int PROPERITY_PERMISSON_NO				= 0; 	// NOTIFY ONLY
	public static final int PROPERITY_PERMISSON_GET				= 1; 	// GET ONLY
	public static final int PROPERITY_PERMISSON_SET				= 2; 	// SET ONLY
	public static final int PROPERITY_PERMISSON_GET_SET 	= 3;	// GET_SET		
		
	public static final int PROTOCOL_FORMAT_HEAD 		= 0x68;//协议格式头
	public static final int PROTOCOL_FORMAT_TAIL 			= 0x10;//协议格式尾

	// Cmd定义
	public static final int CMD_CHANNEL_SWITCH 						= 0x01;// 信号切换
	public static final int CMD_SET_VOLUME 								= 0x02;// 音量设置
	public static final int CMD_SCAN_FREQ_SWITCH 					= 0x03;// 扫频开关
	public static final int CMD_QUERY_MODULE_STATUS 			= 0x04;// 查询模块收发状态
	public static final int CMD_QUERY_SIGNAL_STRENGTH 		= 0x05;// 查询信号强度
	public static final int CMD_CALL_STATUS 							= 0x06;// 开关主呼，上传主呼被呼状态
	public static final int CMD_MESSAGE_STATUS 						= 0x07;// 短信
	public static final int CMD_ALARM_STATUS 							= 0x09;// 紧急报警
	public static final int CMD_EXTERN 										= 0x0A;// 增强扩展命令
	public static final int CMD_SET_MIC 									= 0x0B;// 设置MIC增益
	public static final int CMD_SET_POWER 								= 0x0C;// 设置省电模式
	public static final int CMD_SET_FREQ 									= 0x0D;// 设置收发频率
	public static final int CMD_SET_NETWORK 							= 0x0E;// 设置中继/脱网
	public static final int CMD_QUERY_CALL_CONTACTS 			= 0x10;// 查询呼叫联系人
	public static final int CMD_QUERY_MESSAGE_CONTENT 		= 0x11;// 查询短信内容
	public static final int CMD_SQUELCH_LEVEL		 					= 0x12;// 设置静噪等级
	public static final int CMD_TONE_TYPE 								= 0x13;// 设置亚音类型
	public static final int CMD_TONE_FREQ 								= 0x14;// 设置亚音频率或编码
	public static final int CMD_MONITOR_SWITCH 					= 0x15;// 设置亚音类型
	public static final int CMD_SEND_POWER 							= 0x17;// 设置发射功率
	public static final int CMD_SET_CONTACTS 							= 0x18;// 设置联系人
	public static final int CMD_ENCRYPTION_SWITCH 				= 0x19;// 设置加密开关
	public static final int CMD_INIT_STATUS 							= 0x1A;// 查询初始化状态
	public static final int CMD_QUERY_CONTACTS 					= 0x22;// 查询联系人
	public static final int CMD_QUERY_DEVICE_NUMBER 			= 0x24;// 查询本机号
	public static final int CMD_QUERY_VERSION 						= 0x25;// 查询软件版本号
	public static final int CMD_QUERY_SCAN_STATUS 				= 0x27;// 查询扫频状态
	public static final int CMD_QUERY_ENCRYPTION_STATUS 	= 0x28;// 查询加密状态

	// Data Send Type
	public static final int DATA_READ 			= 0x00;// 读
	public static final int DATA_WRITE 			= 0x01;// 写
	public static final int DATA_UPLOAD 		= 0x02;// 上传

	// Ret Result
	public static final int RET_SUCCESS 									= 0x00;// 设置成功
	public static final int RET_BUSY 											= 0x01;// 模块繁忙或者设置失败
	public static final int RET_CHANNEL_ERROR 						= 0x02;// 无此信道或信道错误
	public static final int RET_MODULE_DIE 								= 0x07;// 模块被毙
	public static final int RET_CHECKSUM_ERROR 						= 0x09;// 校验错误
	public static final int RET_CALL_ACTIVE_OVER 					= 0x62;// 主呼结束
	public static final int RET_BS_ACTIVE_TIMEOUT 					= 0x6C;// BS激活超时
	public static final int RET_REJECT_SENDING 						= 0x6D;// 拒绝发送
	public static final int RET_CALL_ACTIVE_TIMEOUT 				= 0x6E;// 主呼超时
	public static final int RET_BE_CALLED_OVER 						= 0x6F;// 被呼结束
	public static final int RET_SEND_MESSAGE_SUCCESS 			= 0x70;// 短信发送成功
	public static final int RET_RECV_PACKAGE_TIMEOUT 			= 0x7E;// 接收反馈包超时
	public static final int RET_INTERPHONE_CHECK_SUCCESS 	= 0xA1;// 对讲机检测成功
	public static final int RET_CALL_PROPMT_SUCCESS 			= 0xA2;// 呼叫提示成功
	public static final int RET_REMOTE_MONITOR_SUCCESS 		= 0xA3;// 远程监听成功
	public static final int RET_REMOTE_KILL_SUCCESS 				= 0xA4;// 对讲机遥毙成功
	public static final int RET_REMOTE_ACTIVE_SUCCESS 			= 0xA5;// 对讲机激活成功
	public static final int RET_DECODE_FAILED 							= 0xAF;// 解码失败	

	
	// Alarm status
	public static final int ALARM_ON 		= 	0x01;// 开启紧急报警
	public static final int ALARM_OFF 	=  0xFF;// 关闭紧急报警

	// Extern Fun ID
	public static final int EXTERN_FUN_CHECKING 				= 0x01;// 对讲机检测
	public static final int EXTERN_FUN_CALL_PROMPT 			= 0x01;// 呼叫提示
	public static final int EXTERN_FUN_REMOTE_MONITOR 	= 0x01;// 远程监听
	public static final int EXTERN_FUN_REMOTE_KILL 			= 0x01;// 对讲机遥毙
	public static final int EXTERN_FUN_ACTIVE 						= 0x01;// 对讲机激活

	// Module Status
	public static final int MODULE_STATUS_SENDING				= 0x01;// 正在接收
	public static final int MODULE_STATUS_RECEIVING 		= 0x02;// 正在发射
	public static final int MODULE_STATUS_STANDBY 			= 0x03;// 待机

	// Call Type
	public static final int CALL_TYPE_PERSONAL 		= 0x01;// 个呼
	public static final int CALL_TYPE_GROUP 			= 0x02;// 组呼
	public static final int CALL_TYPE_NO_ADDRESS 	= 0x03;// 无地址呼
	public static final int CALL_TYPE_BROADCAST 	= 0x04;// 全呼和广播
	
	// 所有支持的属性集
	public static final int[] INTERPHONE_PROPERITIES = new int[] { 
			DeviceInterfaceProperties.DIM_INTERPHONE_CHANNEL_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_RECEIVE_VOLUME_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_SCAN_FREQ_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_SIGNAL_STRENGTH_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_CALLOUT_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_CALL_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_CALLING_CONTACTS_INFO_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_SEND_MESSAGE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_ALARM_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REQ_CHECK_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_CALL_PROMPT_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_MONITOR_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_KILL_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_ACTIVE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_MIC_GAIN_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_POWER_MODE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_COMN_FREQ_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_RELAY_MODE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_SQUELCH_LEVEL_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_TONE_TYPE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_TONE_FREQ_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_MONITOR_STATUS_PROPERTY	,
			DeviceInterfaceProperties.DIM_INTERPHONE_SENDING_POWER_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_CALL_CONTACT_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_ENCRYPTION_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_INIT_STATUS_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_CONTACTS_INFO_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_NUMBER_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_VERSION_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_RET_ERROR_CODE_PROPERTY,
			DeviceInterfaceProperties.DIM_INTERPHONE_REQ_CMD_PROPERTY
			
	};
	// 属性读写权限表
	public static final SparseIntArray INTERPHONE_PROPERITY_PERMISSION_TABLE = new SparseIntArray();
	static
	{
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CHANNEL_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RECEIVE_VOLUME_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SCAN_FREQ_STATUS_PROPERTY	, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_STATUS_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SIGNAL_STRENGTH_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALLOUT_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALL_STATUS_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALLING_CONTACTS_INFO_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALLING_CONTACTS_INFO_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SEND_MESSAGE_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RELAY_MODE_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ALARM_STATUS_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REQ_CHECK_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_CALL_PROMPT_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_MONITOR_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_KILL_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_ACTIVE_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_MIC_GAIN_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_POWER_MODE_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_COMN_FREQ_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RELAY_MODE_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SQUELCH_LEVEL_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_TONE_TYPE_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_TONE_FREQ_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_MONITOR_STATUS_PROPERTY	, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SENDING_POWER_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALL_CONTACT_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ENCRYPTION_STATUS_PROPERTY, PROPERITY_PERMISSON_SET);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_INIT_STATUS_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CONTACTS_INFO_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_NUMBER_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_VERSION_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ENCRYPTION_STATUS_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RET_ERROR_CODE_PROPERTY, PROPERITY_PERMISSON_NO);
		INTERPHONE_PROPERITY_PERMISSION_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_REQ_CMD_PROPERTY, PROPERITY_PERMISSON_SET);
	}

	// 属性值类型表
	public static final SparseIntArray INTERPHONE_PROPERITY_DATA_TYPE_TABLE = new SparseIntArray();
	static
	{
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CHANNEL_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RECEIVE_VOLUME_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SCAN_FREQ_STATUS_PROPERTY	, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_STATUS_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SIGNAL_STRENGTH_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALLOUT_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALL_STATUS_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALLING_CONTACTS_INFO_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SEND_MESSAGE_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RELAY_MODE_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ALARM_STATUS_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REQ_CHECK_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_CALL_PROMPT_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_MONITOR_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_REMOTE_KILL_PROPERTY, DATA_TYPE_STRING);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_EXTERN_ACTIVE_PROPERTY, DATA_TYPE_STRING);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_MIC_GAIN_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_POWER_MODE_PROPERTY, DATA_TYPE_INT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_COMN_FREQ_PROPERTY, DATA_TYPE_INT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RELAY_MODE_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SQUELCH_LEVEL_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_TONE_TYPE_PROPERTY, DATA_TYPE_INT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_TONE_FREQ_PROPERTY, DATA_TYPE_FLOAT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_MONITOR_STATUS_PROPERTY	, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_SENDING_POWER_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CALL_CONTACT_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ENCRYPTION_STATUS_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_INIT_STATUS_PROPERTY, DATA_TYPE_INTEGER);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_CONTACTS_INFO_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_DEVICE_NUMBER_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_VERSION_PROPERTY, DATA_TYPE_STRING_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_ENCRYPTION_STATUS_PROPERTY, DATA_TYPE_INT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_RET_ERROR_CODE_PROPERTY, DATA_TYPE_INT_ARRAY);
		INTERPHONE_PROPERITY_DATA_TYPE_TABLE.put(DeviceInterfaceProperties.DIM_INTERPHONE_REQ_CMD_PROPERTY, DATA_TYPE_INTEGER);
	}

	
	public static int getProperityDataType(int prop)
	{
		return (INTERPHONE_PROPERITY_DATA_TYPE_TABLE.indexOfKey(prop) >= 0) ? INTERPHONE_PROPERITY_DATA_TYPE_TABLE.get(prop) : -1;
	}

	public static int getProperityPermission(int prop)
	{
		return (INTERPHONE_PROPERITY_PERMISSION_TABLE.indexOfKey(prop) >= 0) ? INTERPHONE_PROPERITY_PERMISSION_TABLE.get(prop) : -1;
	}
}
